import fg from 'fast-glob';
import type { WalkOptions } from './types.js';

// ---------------------------------------------------------------------------
// Default glob patterns
// ---------------------------------------------------------------------------

const DEFAULT_INCLUDE: string[] = ['**/*.{js,jsx,ts,tsx}'];

const DEFAULT_IGNORE: string[] = [
  // Dependencies
  '**/node_modules/**',
  // Build artefacts
  '**/dist/**',
  '**/build/**',
  '**/.next/**',
  '**/coverage/**',
  // Test files
  '**/*.test.*',
  '**/*.spec.*',
  '**/__tests__/**',
  '**/__mocks__/**',
  // Type declarations generated by tsc / others
  '**/*.d.ts',
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Walk a project root and return the set of candidate source files to analyse.
 *
 * @param rootDir - Absolute path to the project root.
 * @param options - Optional overrides for include/ignore patterns.
 * @returns Sorted array of **absolute** file paths.
 */
export async function walkProject(
  rootDir: string,
  options: WalkOptions = {},
): Promise<string[]> {
  // Resolve include patterns
  const includePatterns: string[] =
    options.includePatterns !== undefined
      ? [...options.includePatterns, ...(options.include ?? [])]
      : [...DEFAULT_INCLUDE, ...(options.include ?? [])];

  // Resolve ignore patterns
  const ignorePatterns: string[] =
    options.ignorePatterns !== undefined
      ? [...options.ignorePatterns, ...(options.ignore ?? [])]
      : [...DEFAULT_IGNORE, ...(options.ignore ?? [])];

  const files = await fg(includePatterns, {
    cwd: rootDir,
    absolute: true,
    ignore: ignorePatterns,
    followSymbolicLinks: false,
    // Reproducible ordering across platforms
    onlyFiles: true,
  });

  // Sort for determinism — fast-glob order can vary by OS
  return files.sort();
}
